name: ci

on:
  push:
    branches: master

env:
  REGISTRY: ghcr.io
  ORG_NAME: aginic-ventures
  IMAGE_NAME: nginx-jwt
  NGINX_VERSION: 1.22.0

jobs:
  nginx-build:
    name: Build and push nginx dockerfile
    runs-on: ubuntu-latest
    # permissions for GitHub container registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        name: Build Dockerfile
        with:
          file: Dockerfile
          context: .
          build-args: |
            ORG_NAME=${{ env.ORG_NAME }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            NGINX_VERSION=${{ env.NGINX_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}:${{ env.NGINX_VERSION }}
          push: true
